// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: adventures/v1/adventures.proto

/*
Package adventuresv1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package adventuresv1

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_AdventureService_ListAdventures_0(ctx context.Context, marshaler runtime.Marshaler, client AdventureServiceClient, req *http.Request, pathParams map[string]string) (AdventureService_ListAdventuresClient, runtime.ServerMetadata, error) {
	var protoReq ListAdventuresRequest
	var metadata runtime.ServerMetadata

	stream, err := client.ListAdventures(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

func request_AdventureService_CreateAdventure_0(ctx context.Context, marshaler runtime.Marshaler, client AdventureServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateAdventureRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateAdventure(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_AdventureService_CreateAdventure_0(ctx context.Context, marshaler runtime.Marshaler, server AdventureServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateAdventureRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateAdventure(ctx, &protoReq)
	return msg, metadata, err

}

func request_AdventureService_GetAdventure_0(ctx context.Context, marshaler runtime.Marshaler, client AdventureServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetAdventureRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "id")
	}

	protoReq.Id, err = runtime.Int32(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	msg, err := client.GetAdventure(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_AdventureService_GetAdventure_0(ctx context.Context, marshaler runtime.Marshaler, server AdventureServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetAdventureRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "id")
	}

	protoReq.Id, err = runtime.Int32(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	msg, err := server.GetAdventure(ctx, &protoReq)
	return msg, metadata, err

}

func request_AdventureService_UpdateAdventure_0(ctx context.Context, marshaler runtime.Marshaler, client AdventureServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateAdventureRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "id")
	}

	protoReq.Id, err = runtime.Int32(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	msg, err := client.UpdateAdventure(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_AdventureService_UpdateAdventure_0(ctx context.Context, marshaler runtime.Marshaler, server AdventureServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq UpdateAdventureRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "id")
	}

	protoReq.Id, err = runtime.Int32(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	msg, err := server.UpdateAdventure(ctx, &protoReq)
	return msg, metadata, err

}

func request_AdventureService_DeleteAdventure_0(ctx context.Context, marshaler runtime.Marshaler, client AdventureServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DeleteAdventureRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "id")
	}

	protoReq.Id, err = runtime.Int32(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	msg, err := client.DeleteAdventure(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_AdventureService_DeleteAdventure_0(ctx context.Context, marshaler runtime.Marshaler, server AdventureServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DeleteAdventureRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "id")
	}

	protoReq.Id, err = runtime.Int32(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	msg, err := server.DeleteAdventure(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterAdventureServiceHandlerServer registers the http handlers for service AdventureService to "mux".
// UnaryRPC     :call AdventureServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterAdventureServiceHandlerFromEndpoint instead.
func RegisterAdventureServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server AdventureServiceServer) error {

	mux.Handle("GET", pattern_AdventureService_ListAdventures_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		err := status.Error(codes.Unimplemented, "streaming calls are not yet supported in the in-process transport")
		_, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		return
	})

	mux.Handle("POST", pattern_AdventureService_CreateAdventure_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/adventures.v1.AdventureService/CreateAdventure", runtime.WithHTTPPathPattern("/api/v1/adventures"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_AdventureService_CreateAdventure_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AdventureService_CreateAdventure_0(annotatedContext, mux, outboundMarshaler, w, req, response_AdventureService_CreateAdventure_0{resp}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_AdventureService_GetAdventure_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/adventures.v1.AdventureService/GetAdventure", runtime.WithHTTPPathPattern("/api/v1/adventures/{id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_AdventureService_GetAdventure_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AdventureService_GetAdventure_0(annotatedContext, mux, outboundMarshaler, w, req, response_AdventureService_GetAdventure_0{resp}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("PUT", pattern_AdventureService_UpdateAdventure_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/adventures.v1.AdventureService/UpdateAdventure", runtime.WithHTTPPathPattern("/api/v1/adventures/{id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_AdventureService_UpdateAdventure_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AdventureService_UpdateAdventure_0(annotatedContext, mux, outboundMarshaler, w, req, response_AdventureService_UpdateAdventure_0{resp}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("DELETE", pattern_AdventureService_DeleteAdventure_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/adventures.v1.AdventureService/DeleteAdventure", runtime.WithHTTPPathPattern("/api/v1/adventures/{id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_AdventureService_DeleteAdventure_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AdventureService_DeleteAdventure_0(annotatedContext, mux, outboundMarshaler, w, req, response_AdventureService_DeleteAdventure_0{resp}, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterAdventureServiceHandlerFromEndpoint is same as RegisterAdventureServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterAdventureServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterAdventureServiceHandler(ctx, mux, conn)
}

// RegisterAdventureServiceHandler registers the http handlers for service AdventureService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterAdventureServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterAdventureServiceHandlerClient(ctx, mux, NewAdventureServiceClient(conn))
}

// RegisterAdventureServiceHandlerClient registers the http handlers for service AdventureService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "AdventureServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "AdventureServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "AdventureServiceClient" to call the correct interceptors.
func RegisterAdventureServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client AdventureServiceClient) error {

	mux.Handle("GET", pattern_AdventureService_ListAdventures_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/adventures.v1.AdventureService/ListAdventures", runtime.WithHTTPPathPattern("/api/v1/adventures"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_AdventureService_ListAdventures_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AdventureService_ListAdventures_0(annotatedContext, mux, outboundMarshaler, w, req, func() (proto.Message, error) {
			res, err := resp.Recv()
			return response_AdventureService_ListAdventures_0{res}, err
		}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_AdventureService_CreateAdventure_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/adventures.v1.AdventureService/CreateAdventure", runtime.WithHTTPPathPattern("/api/v1/adventures"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_AdventureService_CreateAdventure_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AdventureService_CreateAdventure_0(annotatedContext, mux, outboundMarshaler, w, req, response_AdventureService_CreateAdventure_0{resp}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_AdventureService_GetAdventure_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/adventures.v1.AdventureService/GetAdventure", runtime.WithHTTPPathPattern("/api/v1/adventures/{id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_AdventureService_GetAdventure_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AdventureService_GetAdventure_0(annotatedContext, mux, outboundMarshaler, w, req, response_AdventureService_GetAdventure_0{resp}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("PUT", pattern_AdventureService_UpdateAdventure_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/adventures.v1.AdventureService/UpdateAdventure", runtime.WithHTTPPathPattern("/api/v1/adventures/{id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_AdventureService_UpdateAdventure_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AdventureService_UpdateAdventure_0(annotatedContext, mux, outboundMarshaler, w, req, response_AdventureService_UpdateAdventure_0{resp}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("DELETE", pattern_AdventureService_DeleteAdventure_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/adventures.v1.AdventureService/DeleteAdventure", runtime.WithHTTPPathPattern("/api/v1/adventures/{id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_AdventureService_DeleteAdventure_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AdventureService_DeleteAdventure_0(annotatedContext, mux, outboundMarshaler, w, req, response_AdventureService_DeleteAdventure_0{resp}, mux.GetForwardResponseOptions()...)

	})

	return nil
}

type response_AdventureService_ListAdventures_0 struct {
	proto.Message
}

func (m response_AdventureService_ListAdventures_0) XXX_ResponseBody() interface{} {
	response := m.Message.(*ListAdventuresResponse)
	return response.Adventure
}

type response_AdventureService_CreateAdventure_0 struct {
	proto.Message
}

func (m response_AdventureService_CreateAdventure_0) XXX_ResponseBody() interface{} {
	response := m.Message.(*CreateAdventureResponse)
	return response.Adventure
}

type response_AdventureService_GetAdventure_0 struct {
	proto.Message
}

func (m response_AdventureService_GetAdventure_0) XXX_ResponseBody() interface{} {
	response := m.Message.(*GetAdventureResponse)
	return response.Adventure
}

type response_AdventureService_UpdateAdventure_0 struct {
	proto.Message
}

func (m response_AdventureService_UpdateAdventure_0) XXX_ResponseBody() interface{} {
	response := m.Message.(*UpdateAdventureResponse)
	return response.Adventure
}

type response_AdventureService_DeleteAdventure_0 struct {
	proto.Message
}

func (m response_AdventureService_DeleteAdventure_0) XXX_ResponseBody() interface{} {
	response := m.Message.(*DeleteAdventureResponse)
	return response.Adventure
}

var (
	pattern_AdventureService_ListAdventures_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"api", "v1", "adventures"}, ""))

	pattern_AdventureService_CreateAdventure_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"api", "v1", "adventures"}, ""))

	pattern_AdventureService_GetAdventure_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3}, []string{"api", "v1", "adventures", "id"}, ""))

	pattern_AdventureService_UpdateAdventure_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3}, []string{"api", "v1", "adventures", "id"}, ""))

	pattern_AdventureService_DeleteAdventure_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3}, []string{"api", "v1", "adventures", "id"}, ""))
)

var (
	forward_AdventureService_ListAdventures_0 = runtime.ForwardResponseStream

	forward_AdventureService_CreateAdventure_0 = runtime.ForwardResponseMessage

	forward_AdventureService_GetAdventure_0 = runtime.ForwardResponseMessage

	forward_AdventureService_UpdateAdventure_0 = runtime.ForwardResponseMessage

	forward_AdventureService_DeleteAdventure_0 = runtime.ForwardResponseMessage
)
