// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: adventures/v1/adventures.proto

package adventuresv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AdventureService_ListAdventures_FullMethodName  = "/adventures.v1.AdventureService/ListAdventures"
	AdventureService_CreateAdventure_FullMethodName = "/adventures.v1.AdventureService/CreateAdventure"
	AdventureService_GetAdventure_FullMethodName    = "/adventures.v1.AdventureService/GetAdventure"
	AdventureService_UpdateAdventure_FullMethodName = "/adventures.v1.AdventureService/UpdateAdventure"
	AdventureService_DeleteAdventure_FullMethodName = "/adventures.v1.AdventureService/DeleteAdventure"
)

// AdventureServiceClient is the client API for AdventureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdventureServiceClient interface {
	ListAdventures(ctx context.Context, in *ListAdventuresRequest, opts ...grpc.CallOption) (AdventureService_ListAdventuresClient, error)
	CreateAdventure(ctx context.Context, in *CreateAdventureRequest, opts ...grpc.CallOption) (*CreateAdventureResponse, error)
	GetAdventure(ctx context.Context, in *GetAdventureRequest, opts ...grpc.CallOption) (*GetAdventureResponse, error)
	UpdateAdventure(ctx context.Context, in *UpdateAdventureRequest, opts ...grpc.CallOption) (*UpdateAdventureResponse, error)
	DeleteAdventure(ctx context.Context, in *DeleteAdventureRequest, opts ...grpc.CallOption) (*DeleteAdventureResponse, error)
}

type adventureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdventureServiceClient(cc grpc.ClientConnInterface) AdventureServiceClient {
	return &adventureServiceClient{cc}
}

func (c *adventureServiceClient) ListAdventures(ctx context.Context, in *ListAdventuresRequest, opts ...grpc.CallOption) (AdventureService_ListAdventuresClient, error) {
	stream, err := c.cc.NewStream(ctx, &AdventureService_ServiceDesc.Streams[0], AdventureService_ListAdventures_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &adventureServiceListAdventuresClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AdventureService_ListAdventuresClient interface {
	Recv() (*ListAdventuresResponse, error)
	grpc.ClientStream
}

type adventureServiceListAdventuresClient struct {
	grpc.ClientStream
}

func (x *adventureServiceListAdventuresClient) Recv() (*ListAdventuresResponse, error) {
	m := new(ListAdventuresResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *adventureServiceClient) CreateAdventure(ctx context.Context, in *CreateAdventureRequest, opts ...grpc.CallOption) (*CreateAdventureResponse, error) {
	out := new(CreateAdventureResponse)
	err := c.cc.Invoke(ctx, AdventureService_CreateAdventure_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adventureServiceClient) GetAdventure(ctx context.Context, in *GetAdventureRequest, opts ...grpc.CallOption) (*GetAdventureResponse, error) {
	out := new(GetAdventureResponse)
	err := c.cc.Invoke(ctx, AdventureService_GetAdventure_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adventureServiceClient) UpdateAdventure(ctx context.Context, in *UpdateAdventureRequest, opts ...grpc.CallOption) (*UpdateAdventureResponse, error) {
	out := new(UpdateAdventureResponse)
	err := c.cc.Invoke(ctx, AdventureService_UpdateAdventure_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adventureServiceClient) DeleteAdventure(ctx context.Context, in *DeleteAdventureRequest, opts ...grpc.CallOption) (*DeleteAdventureResponse, error) {
	out := new(DeleteAdventureResponse)
	err := c.cc.Invoke(ctx, AdventureService_DeleteAdventure_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdventureServiceServer is the server API for AdventureService service.
// All implementations should embed UnimplementedAdventureServiceServer
// for forward compatibility
type AdventureServiceServer interface {
	ListAdventures(*ListAdventuresRequest, AdventureService_ListAdventuresServer) error
	CreateAdventure(context.Context, *CreateAdventureRequest) (*CreateAdventureResponse, error)
	GetAdventure(context.Context, *GetAdventureRequest) (*GetAdventureResponse, error)
	UpdateAdventure(context.Context, *UpdateAdventureRequest) (*UpdateAdventureResponse, error)
	DeleteAdventure(context.Context, *DeleteAdventureRequest) (*DeleteAdventureResponse, error)
}

// UnimplementedAdventureServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAdventureServiceServer struct {
}

func (UnimplementedAdventureServiceServer) ListAdventures(*ListAdventuresRequest, AdventureService_ListAdventuresServer) error {
	return status.Errorf(codes.Unimplemented, "method ListAdventures not implemented")
}
func (UnimplementedAdventureServiceServer) CreateAdventure(context.Context, *CreateAdventureRequest) (*CreateAdventureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAdventure not implemented")
}
func (UnimplementedAdventureServiceServer) GetAdventure(context.Context, *GetAdventureRequest) (*GetAdventureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdventure not implemented")
}
func (UnimplementedAdventureServiceServer) UpdateAdventure(context.Context, *UpdateAdventureRequest) (*UpdateAdventureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAdventure not implemented")
}
func (UnimplementedAdventureServiceServer) DeleteAdventure(context.Context, *DeleteAdventureRequest) (*DeleteAdventureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAdventure not implemented")
}

// UnsafeAdventureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdventureServiceServer will
// result in compilation errors.
type UnsafeAdventureServiceServer interface {
	mustEmbedUnimplementedAdventureServiceServer()
}

func RegisterAdventureServiceServer(s grpc.ServiceRegistrar, srv AdventureServiceServer) {
	s.RegisterService(&AdventureService_ServiceDesc, srv)
}

func _AdventureService_ListAdventures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListAdventuresRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdventureServiceServer).ListAdventures(m, &adventureServiceListAdventuresServer{stream})
}

type AdventureService_ListAdventuresServer interface {
	Send(*ListAdventuresResponse) error
	grpc.ServerStream
}

type adventureServiceListAdventuresServer struct {
	grpc.ServerStream
}

func (x *adventureServiceListAdventuresServer) Send(m *ListAdventuresResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AdventureService_CreateAdventure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdventureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventureServiceServer).CreateAdventure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdventureService_CreateAdventure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventureServiceServer).CreateAdventure(ctx, req.(*CreateAdventureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdventureService_GetAdventure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdventureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventureServiceServer).GetAdventure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdventureService_GetAdventure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventureServiceServer).GetAdventure(ctx, req.(*GetAdventureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdventureService_UpdateAdventure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdventureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventureServiceServer).UpdateAdventure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdventureService_UpdateAdventure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventureServiceServer).UpdateAdventure(ctx, req.(*UpdateAdventureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdventureService_DeleteAdventure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdventureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventureServiceServer).DeleteAdventure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdventureService_DeleteAdventure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventureServiceServer).DeleteAdventure(ctx, req.(*DeleteAdventureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdventureService_ServiceDesc is the grpc.ServiceDesc for AdventureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdventureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adventures.v1.AdventureService",
	HandlerType: (*AdventureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAdventure",
			Handler:    _AdventureService_CreateAdventure_Handler,
		},
		{
			MethodName: "GetAdventure",
			Handler:    _AdventureService_GetAdventure_Handler,
		},
		{
			MethodName: "UpdateAdventure",
			Handler:    _AdventureService_UpdateAdventure_Handler,
		},
		{
			MethodName: "DeleteAdventure",
			Handler:    _AdventureService_DeleteAdventure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAdventures",
			Handler:       _AdventureService_ListAdventures_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "adventures/v1/adventures.proto",
}
